site_name: Scientific Computing (edu)
site_description: Educational materials for scientific and parallel computing
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/scientific-computing-edu
repo_url: https://github.com/fluidnumerics/scientific-computing-edu
edit_uri: edit/main/docs/mkdocs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: index.md
  - Portable GPU Programming:
    - Hardware:
      - GPU Accelerated Platforms: GPU/Hardware/GPU-Accelerated-Platforms.md
      - Estimating Performance: GPU/Hardware/Estimating-Performance.md
      - GPU Specifications Table: GPU/Hardware/GPU-Specifications.md
    - OpenMP GPU Offloading: 
      - Basics: GPU/OpenMP/Basics.md
    - HIP and HIPFort: 
      - Basics: GPU/HIP/Basics.md
    - Benchmarking your hardware:
      - PCI: Benchmarks/PCI.md
      - Memory: Benchmarks/Memory.md
      - Compute: Benchmarks/Compute.md
      - Multi-GPU Communications: Benchmarks/MPI_GPU.md
    - Performance Topics:
      - Coalesced Memory Addressing: Performance/Coalesced.md
      - Shared Memory Usage: Performance/SharedMemory.md
      - Occupancy: Performance/Occupancy.md 
      - Asynchronous Operations: Performance/Asynchronous.md
    - Multi-GPU Topics:
      - Task Affinity: MultiGPU/Affinity.md
      - GPU Direct Communications: MultiGPU/GPUDirect.md
    - Profiling Applications:
      - Basics : Profiling/index.md
      - Profiling with rocprof: Profiling/rocprof.md
    - For System Administrators:
      - Build amdclang/flang with AMD and Nvidia bitcodes: SysAdmin/AMDClangFlang.md
      - Installing OpenMPI with AMD GPU Support: SysAdmin/OpenMPIAMDGPU.md
    - Codelabs:
      - Build a GPU Accelerated Application with HIP in C/C++: codelabs/build-a-gpu-app-hip-c/index.html
      - Build a GPU Accelerated Application with HIPFort in Fortran: codelabs/build-a-gpu-app-hip-fortran/index.html
      - Build a GPU Accelerated Application with OpenMP in C/C++: codelabs/build-a-gpu-app-openmp-c/index.html
      - Build a GPU Accelerated Application with OpenMP in Fortran: codelabs/build-a-gpu-app-openmp-fortran/index.html

theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo-fluid-numerics.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins: 
    - glightbox
