site_name: Scientific Computing (edu)
site_description: Educational materials for scientific and parallel computing
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/scientific-computing-edu
repo_url: https://github.com/fluidnumerics/scientific-computing-edu
edit_uri: edit/main/docs/mkdocs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: index.md
  - Portable GPU Programming:
    - Getting to know your hardware (Part 1): GPU/Hardware-Part1.md
    - Codelabs:
      - Build a GPU Accelerated Application with HIP in C/C++: codelabs/build-a-gpu-app-hip-c/index.html
      - Build a GPU Accelerated Application with HIPFort in Fortran: codelabs/build-a-gpu-app-hip-fortran/index.html
      - Build a GPU Accelerated Application with OpenMP in C/C++: codelabs/build-a-gpu-app-openmp-c/index.html
      - Build a GPU Accelerated Application with OpenMP in Fortran: codelabs/build-a-gpu-app-openmp-fortran/index.html

theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo-fluid-numerics.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins: 
    - glightbox
